version: '3.1'

services:
  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    volumes:
      - "neo4j-data:/data"

volumes:
  neo4j-data: